routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Mail\VerificationEmail;
use Illuminate\Support\Facades\Mail;
use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SiteController@index')->name('index');
Route::match(['get', 'post'], '/dapatkan-kategori-produk', 'SiteController@dapatkanKategoriProduk')->name('dapatkan.kategori.produk');
Route::get('/produk', 'SiteController@dapatkanProduk')->name('dapatkan.produk');
Route::get('/produk/{id}', 'SiteController@spesifikProduk')->name('spesifik.produk');
Route::get('/produk-promo', 'SiteController@dapatkanProdukPromo')->name('dapatkan.produk.promo');
Route::get('/login-user', 'UserController@loginUser')->name('login.user');
Route::get('/daftar-baru', 'UserController@daftarUserBaru')->name('daftar.user.baru');
Route::get('/verifikasi-token/{token}', 'Auth\RegisterController@verifikasiToken')->name('verifikasi.token');
Route::get('/verifikasi-ulang/{id}', 'Auth\LoginController@verifikasiUlang')->name('verifikasi.ulang');
Route::post('/login-user', 'Auth\LoginController@authenticate')->name('post.login.user');
Route::get('/web-kategori-produk/{id}', 'SiteController@webKategoriProduk')->name('web.kategori.produk');
Route::post('/daftar-baru', 'Auth\RegisterController@create')->name('post.daftar.baru');

Route::group(['middleware' => ['auth', 'checkRole:admin,user', 'checkVerify:true']], function() {
    Route::post('/tambah-keranjang', 'BelanjaController@tambahKeranjang')->name('tambah.keranjang');
    Route::get('/hapusItemKeranjang/{id}', 'BelanjaController@hapusItemKeranjang')->name('hapus.item.keranjang');
    Route::get('/cekout', 'BelanjaController@cekout')->name('cekout');
    Route::post('/dapatkan-list-paket', 'BelanjaController@dapatkanListPaket')->name('dapatkan.list.paket');
    Route::post('/hitung-biaya-kirim', 'BelanjaController@hitungBiayaKirim')->name('hitung.biaya.kirim');
    Route::post('/proses-pesanan', 'BelanjaController@prosesPesanan')->name('proses.pesanan');    
});

Route::group(['middleware' => ['auth', 'checkRole:admin,user']], function() {
    Route::get('/profile/{id}', 'UserController@profile')->name('profile');
    Route::get('/rubah-password/{id}', 'UserController@rubahPassword')->name('rubah.password');
    Route::post('/update-user/{user}', 'UserController@updateUser')->name('update.user');
    Route::post('/rubah-password/{user}', 'UserController@rubahPassword')->name('rubah.password');
    
    Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
});

//miscelaneous
Route::post('/cari-produk-berdasarkan-kategori-id', 'ProdukController@cariProdukBerdasarkanKategoriId')->name('cari.produk.berdasarkan.kategori.id');
Route::post('/cari-provinsi-id', 'UserController@cariProvinsiId')->name('cari.provinsi.id');
Route::post('/cari-list-kota', 'UserController@cariListKota')->name('cari.list.kota');

Route::group(['middleware' => ['auth', 'checkRole:admin', 'checkVerify:true']], function() {
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

        //master
        Route::resource('satuan', 'SatuanController');
        Route::resource('kota', 'KotaController');
        Route::resource('kategori-user', 'KategoriUserController');
        Route::resource('merek', 'MerekController');
        Route::resource('user', 'UserController');
        Route::resource('jasa-kirim', 'JasaKirimController');
        Route::resource('kategori-produk', 'KategoriProdukController');
        Route::resource('admin-produk', 'ProdukController');

        //transaksi
        Route::get('order', 'OrderController@index')->name('order.index');
        
        //table
        Route::get('tabel-satuan', 'SatuanController@dataTable')->name('table.satuan');
        Route::get('tabel-kota', 'KotaController@dataTable')->name('table.kota');
        Route::get('tabel-merek', 'MerekController@dataTable')->name('table.merek');
        Route::get('tabel-kategori-produk', 'KategoriProdukController@dataTable')->name('table.kategori.produk');
        Route::get('tabel-produk', 'ProdukController@dataTable')->name('table.produk');
        Route::get('tabel-user', 'UserController@dataTable')->name('table.user');
        Route::get('tabel-order', 'OrderController@dataTable')->name('table.order');

        //miscelaneous
        Route::post('/cari-data-produk', 'ProdukController@cariDataProduk')->name('cari.data.produk');
        Route::post('/cari-nama-satuan', 'ProdukController@cariNamaSatuan')->name('cari.nama.satuan');
        Route::post('/cari-merek-logo', 'ProdukController@cariMerekLogo')->name('cari.merek.logo');
        Route::post('/cari-data-supplier', 'ProdukController@cariDataSupplier')->name('cari.data.supplier');
        Route::post('/hitung-harga-diskon', 'ProdukController@hitungHargaDiskon')->name('hitung.harga.diskon');    
        Route::post('/cari-gambar-produk', 'ProdukController@cariGambarProduk')->name('cari.gambar.produk');   
});

Route::get('/desain-email-tagihan', function() {
    return view('email.desain-tagihan');
});

Route::get('/format-uang', function() {
    return view('blank');
});

Route::get('/blank', function() {
    return view('blank');
});


Route::get('/pusher', function() {
    return view('pusher');
});

Route::get('test', function () {
    event(new App\Events\StatusLiked('Someone'));
    return "Event has been sent!";
});

app/Kota.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kota extends Model
{
    protected $table = 'kota';
    protected $fillable = ['kode', 'nama'];
    public $timestamps = false;

    public function user() {
        return $this->hasMany(User::class);
    }

    public function supplier() {
        return $this->hasMany(Supplier::class);
    }
}

app/Http/Controllers/KotaController.php
<?php

namespace App\Http\Controllers;
use App\Kota;
use DataTables;
use Illuminate\Http\Request;

class KotaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sub_title = 'Data Kota'; 
        $form_title = 'Tambah Data Kota';
        return view('admin.master.kota.index', compact(['sub_title', 'form_title']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Kota();
        return view('admin.master.kota.form', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'kode' => 'required|string|min:3|max:3|unique:kota',
            'nama' => 'required|string|max:50',
        ]);
        $model = Kota::create($request->all());
        return $model;    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $model = Kota::findOrFail($id);
        return view('admin.master.kota.tampil', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Kota::findOrFail($id);
        return view('admin.master.kota.form', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'kode' => 'required|string|max:3|unique:kota,id,' . $id,
            'nama' => 'required|string|max:50',
        ]);

        $model = Kota::findOrFail($id);
        $model->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Kota::findOrFail($id);
        $model->delete();
    }

    public function dataTable() 
    {
        $model = Kota::query();
          
        return Datatables::of($model)  
        ->addColumn('aksi', function($model) {
                 return view('layouts.aksi._aksi-master', [
                     'model' => $model,
                     'url_show' => route('kota.show', $model->id),
                     'url_edit' => route('kota.edit', $model->id),
                     'url_destroy' => route('kota.destroy', $model->id)
                 ]);   
            })
            ->rawColumns(['aksi'])
            ->make(true);
    }
}

resources/views/admin/master/kota/form.blade.php
{!! Form::model($model, [
    'route' => $model->exists ? ['kota.update', $model->id] : 'kota.store',
    'method' => $model->exists ? 'PUT' : 'POST'
]) !!}


<div class="row">
    <div class="col-6">
        <div class="form-group">
            @if($model->exists)
                {!! Form::hidden('kode', $model->kode); !!}
                {!! Form::text('kode', null, ['disabled' => 'disabled', 'class' => 'form-control', 'id' => 'kode', 'placeholder' => 'Masukkan kode Satuan']) !!}
            @else 
                {!! Form::text('kode', null, ['class' => 'form-control', 'id' => 'kode', 'placeholder' => 'Masukkan kode Satuan']) !!}
            @endif
        </div>
</div>
    <div class="col-6">
        <div class="form-group">
            {!! Form::text('nama', null, ['class' => 'form-control', 'id' => 'nama', 'placeholder' => 'Masukkan Nama Kota']) !!}
        </div>
    </div>
</div>

{!! Form::close() !!}

resources/views/admin/master/kota/index.blade.php
@extends('layouts.admin')

@push('styles')
    <style>
        #datatable td:nth-child(2) {
            width:60%;
        }
    </style>
@endpush

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <div class="card-body">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-5">
                <div class="card shadow">
                    <div class="card-header bg-warning py-3">
                      <h2 class="font-weight-bold float-left">{{ $sub_title }}</h2>
                      <a href="{{ route('kota.create') }}" data-toggle="modal" tipe="tambah" judul='{{ $form_title }}' 
                             data-backdrop="static" class="btn btn-dark float-right mt-2 btn-sm btn-tampil-modal">
                             <i class="fa fa-plus"></i></a>
                    </div>
                    <div class="card-body">
                        <table id="datatable" class="table table-hover">
                            <thead>
                                <th width="20">KODE</th>
                                <th>NAMA</th>
                                <th width="50">AKSI</th>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                  </div>
              </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function() {
            $('#datatable').DataTable({
            serverSide: true,
            processing: true,
            responsive: true,
            ajax: "{{ route('table.kota') }}",
            columns: [
                { data: 'kode', name: 'kode' },
                { data: 'nama', name: 'nama' },
                { data: 'aksi', name: 'aksi' }
            ],
            language: {
                lengthMenu: 'Tampil _MENU_ rekord per halaman',
                info: 'Tampil hal _PAGE_ dari _PAGES_',
                processing: 'Sedang memproses...',
                search: 'Cari',
                zeroRecords: 'Tidak ditemukan rekord',
                paginate: {
                    first: 'Pertama',
                    last: 'Terakir',
                    next: 'Selanjutnya',
                    previous: 'Sebelumnya',
                },
                infoFiltered: "( filter dari _MAX_ jumlah rekord )"
            }
            })
        })
    </script>
@endpush

resources/views/admin/master/kota/tampil.blade.php
<table class="table table-borderless master-show">
    <tbody>
        <tr>
            <td>Kode</td>
            <td>:</td>
            <td>{{ $model->kode }}</td>
        </tr>
        <tr>
            <td>Nama</td>
            <td>:</td>
            <td>{{ $model->nama }}</td>
        </tr>
    </tbody>
</table>