routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Mail\VerificationEmail;
use Illuminate\Support\Facades\Mail;
use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SiteController@index')->name('index');
Route::match(['get', 'post'], '/dapatkan-kategori-produk', 'SiteController@dapatkanKategoriProduk')->name('dapatkan.kategori.produk');
Route::get('/produk', 'SiteController@dapatkanProduk')->name('dapatkan.produk');
Route::get('/produk/{id}', 'SiteController@spesifikProduk')->name('spesifik.produk');
Route::get('/produk-promo', 'SiteController@dapatkanProdukPromo')->name('dapatkan.produk.promo');
Route::get('/login-user', 'UserController@loginUser')->name('login.user');
Route::get('/daftar-baru', 'UserController@daftarUserBaru')->name('daftar.user.baru');
Route::get('/verifikasi-token/{token}', 'Auth\RegisterController@verifikasiToken')->name('verifikasi.token');
Route::get('/verifikasi-ulang/{id}', 'Auth\LoginController@verifikasiUlang')->name('verifikasi.ulang');
Route::post('/login-user', 'Auth\LoginController@authenticate')->name('post.login.user');
Route::get('/web-kategori-produk/{id}', 'SiteController@webKategoriProduk')->name('web.kategori.produk');
Route::post('/daftar-baru', 'Auth\RegisterController@create')->name('post.daftar.baru');

Route::group(['middleware' => ['auth', 'checkRole:admin,user', 'checkVerify:true']], function() {
    Route::post('/tambah-keranjang', 'BelanjaController@tambahKeranjang')->name('tambah.keranjang');
    Route::get('/hapusItemKeranjang/{id}', 'BelanjaController@hapusItemKeranjang')->name('hapus.item.keranjang');
    Route::get('/cekout', 'BelanjaController@cekout')->name('cekout');
    Route::post('/dapatkan-list-paket', 'BelanjaController@dapatkanListPaket')->name('dapatkan.list.paket');
    Route::post('/hitung-biaya-kirim', 'BelanjaController@hitungBiayaKirim')->name('hitung.biaya.kirim');
    Route::post('/proses-pesanan', 'BelanjaController@prosesPesanan')->name('proses.pesanan');    
});

Route::group(['middleware' => ['auth', 'checkRole:admin,user']], function() {
    Route::get('/profile/{id}', 'UserController@profile')->name('profile');
    Route::get('/rubah-password/{id}', 'UserController@rubahPassword')->name('rubah.password');
    Route::post('/update-user/{user}', 'UserController@updateUser')->name('update.user');
    Route::post('/rubah-password/{user}', 'UserController@rubahPassword')->name('rubah.password');
    
    Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
});

//miscelaneous
Route::post('/cari-produk-berdasarkan-kategori-id', 'ProdukController@cariProdukBerdasarkanKategoriId')->name('cari.produk.berdasarkan.kategori.id');
Route::post('/cari-provinsi-id', 'UserController@cariProvinsiId')->name('cari.provinsi.id');
Route::post('/cari-list-kota', 'UserController@cariListKota')->name('cari.list.kota');

Route::group(['middleware' => ['auth', 'checkRole:admin', 'checkVerify:true']], function() {
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

        //master
        Route::resource('satuan', 'SatuanController');
        Route::resource('kota', 'KotaController');
        Route::resource('kategori-user', 'KategoriUserController');
        Route::resource('merek', 'MerekController');
        Route::resource('user', 'UserController');
        Route::resource('jasa-kirim', 'JasaKirimController');
        Route::resource('kategori-produk', 'KategoriProdukController');
        Route::resource('admin-produk', 'ProdukController');

        //transaksi
        Route::get('order', 'OrderController@index')->name('order.index');
        
        //table
        Route::get('tabel-satuan', 'SatuanController@dataTable')->name('table.satuan');
        Route::get('tabel-kota', 'KotaController@dataTable')->name('table.kota');
        Route::get('tabel-merek', 'MerekController@dataTable')->name('table.merek');
        Route::get('tabel-kategori-produk', 'KategoriProdukController@dataTable')->name('table.kategori.produk');
        Route::get('tabel-produk', 'ProdukController@dataTable')->name('table.produk');
        Route::get('tabel-user', 'UserController@dataTable')->name('table.user');
        Route::get('tabel-order', 'OrderController@dataTable')->name('table.order');

        //miscelaneous
        Route::post('/cari-data-produk', 'ProdukController@cariDataProduk')->name('cari.data.produk');
        Route::post('/cari-nama-satuan', 'ProdukController@cariNamaSatuan')->name('cari.nama.satuan');
        Route::post('/cari-merek-logo', 'ProdukController@cariMerekLogo')->name('cari.merek.logo');
        Route::post('/cari-data-supplier', 'ProdukController@cariDataSupplier')->name('cari.data.supplier');
        Route::post('/hitung-harga-diskon', 'ProdukController@hitungHargaDiskon')->name('hitung.harga.diskon');    
        Route::post('/cari-gambar-produk', 'ProdukController@cariGambarProduk')->name('cari.gambar.produk');   
});

Route::get('/desain-email-tagihan', function() {
    return view('email.desain-tagihan');
});

Route::get('/format-uang', function() {
    return view('blank');
});

Route::get('/blank', function() {
    return view('blank');
});


Route::get('/pusher', function() {
    return view('pusher');
});

Route::get('test', function () {
    event(new App\Events\StatusLiked('Someone'));
    return "Event has been sent!";
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $table = 'order';
    protected $fillable = ['nama', 'kurir', 'paket', 'estimasi', 'ongkir', 'catatan', 'status_pembayaran', 'proses',
      'user_id', 'kabupaten', 'provinsi', 'kode_pos'];

    public function user() {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function produk() {
      return $this->belongsToMany(Produk::class)->withPivot([
        'qty',
        'harga',
        'diskon'
      ]);
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;
use Datatables;


class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sub_title = 'Data Order'; 
        $form_title = 'Tambah Data Order';
        return view('admin.transaksi.order.index', compact(['sub_title', 'form_title']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function dataTable() 
    {
        $model = Order::with('user')->select('order.*');
          
        return Datatables::of($model)  
        ->addColumn('user', function($model) {
            return $model->user->email;
        })
        ->addColumn('aksi', function($model) {
                 return view('layouts.aksi._aksi-master-3', [
                     'model' => $model,
                     'url_show' => route('order.show', $model->id),
                     'url_edit' => route('order.edit', $model->id),
                     'url_destroy' => route('order.destroy', $model->id)
                 ]);   
            })
        ->rawColumns(['aksi'])
        ->make(true);
    }
}

resources/views/admin/transaksi/order/form.blade.php
{!! Form::model($model, [
    'route' => $model->exists ? ['admin-produk.update', $model->id] : 'admin-produk.store',
    'method' => $model->exists ? 'PUT' : 'POST',
    'novalidate' => 'novalidate',
    'files' => 'true'
]) !!}

<div class="card mb-2">
    <div class="card-header bg-success">
        <h6 class="text-white font-weight-bold">Input Data Produk</h6></div>

    <div class="card-body">
        {{ Form::hidden('user_id', Auth::user()->id )}}

        <div class="form-row">
            <div class="col-6">
                <div class="form-group">
                    {!! Form::select('kategori_id', $listKategoriProduk, null, ['id' => 'kategori_id', 
                        'class' => 'form-control form-control-sm']) !!}
                </div>
                <div class="form-group">
                    {!! Form::text('nama', null, ['class' => 'form-control form-control-sm', 'id' => 'nama', 
                        'placeholder' => 'Masukkan Nama Produk']) !!}
                </div>
                <div class="row">
                    <div class="col-4">
                        <div class="form-group">
                            {!! Form::number('qty', null, ['class' => 'form-control form-control-sm', 'id' => 'qty', 
                            'min' => 0, 'placeholder' => 'Quantity']) !!}
                        </div>
                    </div>
                    <div class="col-8">
                        <div class="form-group">
                            {!! Form::select('satuan_id', $listSatuan, null, ['id' => 'satuan_id', 
                            'class' => 'form-control form-control-sm']) !!}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="input-group input-group-sm mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Rp</span>
                            </div>
                            {!! Form::text('harga', null, ['class' => 'form-control form-control-sm', 
                            'id' => 'harga', 
                            'placeholder' => 'Harga Jual']) !!}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="input-group input-group-sm mb-3">
                            {!! Form::number('diskon', null, ['id' => 'diskon', 'min' => 0, 'max' => 100,
                            'class' => 'form-control form-control-sm', 'placeholder' => 'Diskon']) !!}
                            <div class="input-group-append">
                                <span class="input-group-text">%</span>
                            </div>    
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="input-group input-group-sm mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Rp</span>
                            </div>
                            {!! Form::text('harga_beli', null, ['class' => 'form-control form-control-sm', 'id' => 'harga_beli', 
                            'placeholder' => 'Harga Beli']) !!}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            {!! Form::date('tanggal_beli', null, ['id' => 'tanggal_beli', 
                            'class' => 'form-control form-control-sm', 'placeholder' => 'Tanggal_Beli']) !!}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    {!! Form::select('merek_id', $listMerek, null, ['id' => 'merek_id', 
                        'class' => 'form-control form-control-sm']) !!}
                </div>
                <div class="form-group">
                    {!! Form::select('supplier_id', $listSupplier, null, ['id' => 'supplier_id', 
                        'class' => 'form-control form-control-sm']) !!}
                </div>
                <div class="form-group">
                    {!! Form::textarea('ket', null, ['id' => 'ket', 'rows' => '3', 'placeholder' => 'Masukkan Keterangan (boleh dikosongkan)', 
                        'class' => 'form-control form-control-sm']) !!}
                </div>
                <div class="form-group">
                    {{ Form::file('file', ['id' => 'file', 'class' => 'form-control form-control-sm'])}}
                </div>
                @if($model->exists)
                    {{ Form::hidden('nama_file_lama', $model->gambar) }}
                @endif
                <div class="card">
                    <div class="card-header bg-warning">
                        <h6 class="font-weight-bold">Gambar Produk</h6>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <img id="data_gambar" src="{{ url('/web/img/produk/unknown.jpg') }}" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-6 info">
                <div class="card">
                    <div class="card-header bg-info">
                        <h6 class="text-white font-weight-bold">Data Produk</h6>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-4"><label class="label col-form-label-sm">Satuan</label></div>
                            <div class="col-8">{!! Form::text('data_satuan_nama', null, ['class' => 'form-control form-control-sm', 'disabled' => 'disabled', 
                                'id' => 'data_satuan_nama', 'placeholder' => 'Nama Satuan']) !!}</div>
                        </div>
                        <div class="row">
                            <div class="col-4"><label class="label col-form-label-sm">Harga Akhir</label></div>
                            <div class="col-8">{!! Form::text('data_harga_diskon', null, ['class' => 'form-control form-control-sm', 'disabled' => 'disabled', 
                                'id' => 'data_harga_diskon', 'placeholder' => 'Harga Jual']) !!}</div>
                        </div>
                        <div class="row">
                            <div class="col-4"><label class="label col-form-label-sm">Merek</label></div>
                            <div class="col-8"><img id="data_gambar_merek" src="{{ url('/web/img/unknown.jpg') }}" /></div>
                        </div>
                    </div>
                </div>
                
                <div class="card mt-2 info">
                    <div class="card-header bg-info">
                        <h6 class="text-white font-weight-bold">Data Supplier</h6>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-4"><label class="label col-form-label-sm">Alamat</label></div>
                            <div class="col-8">{!! Form::textarea('data_supplier_alamat', null, ['class' => 'form-control form-control-sm', 
                                'rows' => '3', 'disabled' => 'disabled', 
                                'id' => 'data_supplier_alamat', 'placeholder' => 'Alamat Supplier']) !!}</div>
                        </div>
                        <div class="row">
                            <div class="col-4"><label class="label col-form-label-sm">Kota</label></div>
                            <div class="col-8">{!! Form::text('data_supplier_kota', null, ['class' => 'form-control form-control-sm', 'disabled' => 'disabled', 
                                'id' => 'data_supplier_kota', 'placeholder' => 'Kota Supplier']) !!}</div>
                        </div>
                        <div class="row">
                            <div class="col-4"><label class="label col-form-label-sm">PIC</label></div>
                            <div class="col-8">{!! Form::text('data_supplier_pic', null, ['class' => 'form-control form-control-sm', 'disabled' => 'disabled', 
                                'id' => 'data_supplier_pic', 'placeholder' => 'PIC Supplier']) !!}</div>
                        </div>
                        <div class="row">
                            <div class="col-4"><label class="label col-form-label-sm">Telpon</label></div>
                            <div class="col-8">{!! Form::text('data_supplier_telpon', null, ['class' => 'form-control form-control-sm', 'disabled' => 'disabled', 
                                'id' => 'data_supplier_telpon', 'placeholder' => 'Telpon Supplier']) !!}</div>
                        </div>
                    </div>
                </div>
                @if($model->exists )
                    {!! Form::hidden('hidden_harga', $model->harga) !!}
                    {!! Form::hidden('hidden_harga_beli', $model->harga_beli) !!}
                @endif

            </div>
        </div>
    </div>
</div>

{!! Form::close() !!}

resources/views/admin/transaksi/order/index.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <div class="card-body">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="card shadow">
                    <div class="card-header bg-warning py-3">
                      <h2 class="font-weight-bold float-left">{{ $sub_title }}</h2>
                      <a href="{{ route('admin-produk.create') }}" data-toggle="modal" tipe="tambah" 
                            judul='{{ $form_title }}' ukuran='besar' 
                            data-backdrop="static" class="btn btn-dark float-right mt-2 btn-sm btn-tampil-modal">
                             <i class="fa fa-plus"></i></a>
                    </div>
                    <div class="card-body">
                        <table id="datatable" class="table table-hover table-produk">
                            <thead>
                                <th>ID</th>
                                <th>CUSTOMER</th>
                                <th>KURIR</th>
                                <th>SUBTOTAL</th>
                                <th>ONGKIR</th>
                                <th>GRANDTOTAL</th>
                                <th>CATATAN</th>
                                <th>TANGGAL BELI</th>
                                <th>AKSI</th>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                  </div>
              </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>      
        function prosesHargaDiskon() {
            var harga = $('#harga').val();
            var diskon = $('#diskon').val();
            var parHargaNonFormat = accounting.unformat(harga); 
            if (harga.trim() === '') { harga = 0; }
            if (diskon.trim() === '') { diskon = 0; }
            
            var hargaDiskon = hitungDiskon(parHargaNonFormat, diskon);

            if (hargaDiskon === 0) {
                $('#data_harga_diskon').val(0);
            } else {
                $('#data_harga_diskon').val(accounting.formatMoney(hargaDiskon, 'Rp ', 2, ',', '.'));    
            }

            return parHargaNonFormat;
        }

        $(document).ready(function() {
            $('#datatable').DataTable({
                serverSide: true,
                processing: true,
                responsive: true,
                ajax: "{{ route('table.order') }}",
                columns: [
                    { data: 'id', name: 'order.id' },
                    { data: 'nama', name: 'user.nama_lengkap' },
                    { data: 'kurir', name: 'order.kurir' }, 
                    { data: 'subtotal', name: 'order.subtotal' },  
                    { data: 'grantotal', name: 'order.grantotal' },
                    { data: 'catatan', name: 'order.catatan' },    
                    { data: 'aksi', name: 'aksi', orderable: false }
                ],
                language: {
                    lengthMenu: 'Tampil _MENU_ rekord per halaman',
                    info: 'Tampil hal _PAGE_ dari _PAGES_',
                    processing: 'Sedang memproses...',
                    search: 'Cari',
                    zeroRecords: 'Tidak ditemukan rekord',
                    paginate: {
                        first: 'Pertama',
                        last: 'Terakir',
                        next: 'Selanjutnya',
                        previous: 'Sebelumnya',
                    },
                    infoFiltered: "( filter dari _MAX_ jumlah rekord )"
                }
            })

            $('body').on('change', '#satuan_id', function(event){
                event.preventDefault();
                
                if($(this).val() !== '' ) {
                    var satuanId = $(this).val();

                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });

                    $.ajax({ 
                        url: "/cari-nama-satuan",
                        data: { satuanId },
                        type: "POST",
                        success: function(data){
                            var namaSatuan = data;
                            $('#data_satuan_nama').val(namaSatuan);
                        },
                        error: function(error) {
                            console.log(error);
                        }
                    });
                } else {
                    $('#data_satuan_nama').val('');
                }
            });

            $('body').on('keyup', '#harga', function(event){
                event.preventDefault();
                var hargaNonFormat = prosesHargaDiskon();               
                $('#harga').val(formatAngka($(this).val())); 
                bikinHiddenInput('hidden_harga', hargaNonFormat);
            });

            $('body').on('keyup', '#diskon', function(event){
                event.preventDefault();
                prosesHargaDiskon();               
            });

            $('body').on('keyup', '#harga_beli', function(event){
                event.preventDefault();
                $('#harga_beli').val(formatAngka($(this).val())); 

                //bikin hidden value
                var integerHarga = accounting.unformat($(this).val()); 
                bikinHiddenInput('hidden_harga_beli', integerHarga);
            });

            $('body').on('change', '#merek_id', function(event){
                event.preventDefault();
                
                if($(this).val() !== '' ) {
                    var merekId = $(this).val();

                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });

                    $.ajax({ 
                        url: "/cari-merek-logo",
                        data: { merekId },
                        type: "POST",
                        success: function(data){
                            var gambar = data;
                            $('#data_gambar_merek').attr('src', 'web/img/' + gambar);
                        },
                        error: function(error) {
                            console.log(error);
                        }
                    });
                } else {
                    $('#data_gambar_merek').attr('src', 'web/img/unknown.jpg');
                }
            });

            $('body').on('change', '#supplier_id', function(event){
                event.preventDefault();
                
                if($(this).val() !== '' ) {
                    var supplierId = $(this).val();

                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });

                    $.ajax({ 
                        url: "/cari-data-supplier",
                        data: { supplierId },
                        type: "POST",
                        success: function(data){
                            $('#data_supplier_alamat').val(data.alamat);
                            $('#data_supplier_kota').val(data.kota.nama);
                            $('#data_supplier_pic').val(data.pic);
                            $('#data_supplier_telpon').val(data.no_telpon);
                        },
                        error: function(error) {
                            console.log(error);
                        }
                    });
                } else {
                    $('#data_supplier_alamat').val('');
                    $('#data_supplier_kota').val('');
                    $('#data_supplier_pic').val('');
                    $('#data_supplier_telpon').val('');
                }
            });

            $('body').on('change', '#file', function() {
                bacaUrl(this)
            });

            $('#modal').on('shown.bs.modal', function(e){
                var status = $('#modal').attr('tipe');
                if(status === 'edit') {
                    var produkId = $('#modal').attr('kode');
                    var satuanId;
                    var merekId;
                    var supplierId;
                    var harga;
                    var diskon;

                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });

                    //cari data produk
                    $.ajax({ 
                        url: '/cari-data-produk',
                        data: { produkId},
                        async: false,
                        type: "POST",
                        success: function(data){
                            var produk = data;
                            id = produk.id;
                            satuanId = produk.satuan_id;
                            merekId = produk.merek_id;
                            supplierId = produk.supplier_id;
                            harga = produk.harga;
                            harga_beli = produk.harga_beli;
                            gambar = produk.gambar;

                            if(produk.diskon === null) {
                                diskon = 0;
                            } else {
                                diskon = produk.diskon;
                            }

                            $.ajax({ 
                                url: '/cari-nama-satuan',
                                data: { satuanId },
                                type: "POST",
                                success: function(res){
                                    $('#data_satuan_nama').val(res);
                                },
                                error: function(error) {
                                    console.log(error);
                                }
                            });
                            
                            $.ajax({ 
                                url: '/hitung-harga-diskon',
                                data: { harga, diskon },
                                type: "POST",
                                success: function(res){
                                    var hargaDiskon = res;
                                    $('#data_harga_diskon').val(accounting.formatMoney(hargaDiskon, 'Rp ', 2, ',', '.'));  
                                },
                                error: function(error) {
                                    console.log(error);
                                }
                            });

                            $.ajax({ 
                                url: "/cari-merek-logo",
                                data: { merekId },
                                type: "POST",
                                success: function(data){
                                    var gambar = data;
                                    $('#data_gambar_merek').attr('src', 'web/img/' + gambar);
                                },
                                error: function(error) {
                                    console.log(error);
                                }
                            });

                            $.ajax({ 
                                url: "/cari-data-supplier",
                                data: { supplierId },
                                type: "POST",
                                success: function(data){
                                    $('#data_supplier_alamat').val(data.alamat);
                                    $('#data_supplier_kota').val(data.kota.nama);
                                    $('#data_supplier_pic').val(data.pic);
                                    $('#data_supplier_telpon').val(data.no_telpon);
                                },
                                error: function(error) {
                                    console.log(error);
                                }
                            });

                            $.ajax({ 
                                url: "/cari-gambar-produk",
                                data: { id },
                                type: "POST",
                                success: function(data){
                                    var gambar = data;
                                    $('#data_gambar').attr('src', 'web/img/produk/' + gambar);
                                },
                                error: function(error) {
                                    console.log(error);
                                }
                            });

                            //bikin hidden input untuk harga dan harga beli
                            // bikinHiddenInput('hidden_harga', harga);
                            // bikinHiddenInput('hidden_harga_beli', harga_beli);
                            
                        },
                        error: function(error) {
                            console.log(error);
                        }
                    }); 
                }
            });
        })
    </script>
@endpush